### ISSUE TITLE
Support citation keys with underscores?

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/DocumenterCitations.jl#14]
Congrats on the brand new release!
I just tried it with a bib file from https://zbib.org/, and I got a strange error due to a citation key with underscores `rabiner_tutorial_1989`:
```julia
┌ Error: Invalid bibtex key (nested markdown)
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/ZXtrs/src/citations.jl:107
ERROR: Invalid citation: [rabiner*tutorial*1989](@cite)
```
Is it a Markdown thing or a DocumenterCitations thing?

**Comment by fredrikekre** [comment]
Probably you need to escape them `[rabiner\_tutorial\_1989](@cite)`, otherwise it would be Markdown italic style.

**Comment by gdalle** [comment]
Cool, thanks! Might be worth mentioning it in the docs, cause many tools produce such citation keys in the bibtex by default.

**Comment by fredrikekre** [comment]
I don't think the original markdown source is available. In the end of the day you are writing markdown, and `rabiner_tutorial_1989` is not how you write that in markdown, since that means rabiner _tutorial_ 1989. (Actually, looks like the markdown parser on github requires spaces around the underscores).

I agree that it might be unexpected that you are actually writing markdown when looking at this specific context though. At least we can give a better error message.

**Comment by goerz** [comment]
Oh, I had a vague recollection of the original “source code” being available in some attribute of the parsed expression node that Documenter sees…

**Comment by goerz** [comment]
I looked into this a bit more, and I agree: there's no way to access the original source. Since we're stuck with the parsed Markdown AST, the only way to potentially handle this is to roundtrip between the AST and the plain text. One problem with that is that `rabiner_tutorial_1989` roundtrips to `rabiner*tutorial*1989` (since both underscores and asterisks can be used to emphasize in markdown). I could convert that back to underscores, but only if I explicitly forbid asterisks from BiBTeX keys. Probably a fair tradeoff: I can imagine underscores being somewhat commonly used, but not really asterisks.

The [roundtripping isn't completely trivial](https://discourse.julialang.org/t/replace-a-markdown-node-with-markdownast-abstracttrees/103799), but it's probably something I have to do anyway if I want to allow ["citation notes"](https://juliadocs.org/DocumenterCitations.jl/stable/syntax/#Syntax-for-Citations) to include inline markdown syntax.
