### ISSUE TITLE
Curly braces in bibtex Fields

### ISSUE THREAD

**Issue by kellertuer** [JuliaDocs/DocumenterCitations.jl#15]
I just gave this a first try and noticed that my Zotero Export looks like

```
@book{Boumal:2023,
  title = {An {{Introduction}} to {{Optimization}} on {{Smooth Manifolds}}},
  author = {Boumal, Nicolas},
  year = {2023},
  month = mar,
  edition = {First},
  publisher = {{Cambridge University Press}},
  doi = {10.1017/9781009166164},
  isbn = {978-1-00-916616-4}
}
```

I am not sure why Zotero just gives curly braces to everyone, but probably it thinks it is necessary to preserve capitalisation.
Besides me also fighting how the keys will be rendered correctly the current literature then looks like

<img width="810" alt="Screenshot 2023-07-13 at 11 31 30" src="https://github.com/JuliaDocs/DocumenterCitations.jl/assets/115566/562ab41f-6fcc-4028-913a-acde06d54a77">

So all curly braces are kept. In LaTeX these are not kept.
Sure this is also partly Zotero being stupid, but it would be great it curly braces could be removed here in the output

**Comment by kellertuer** [comment]
Ah for the first I was missing a `:` in my references.bib, so now also do Carmo is (with `{do Carmo}`) rendered in the bibliography, but the entries are still like in the screenshot above and I get

```
[ Info: Expanding citations in index.md
┌ Warning: reference for 'doCarmo:1992' could not be found in src/index.md.
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/ZXtrs/src/citations.jl:414
┌ Warning: reference for 'AbsilMahonySepulchre:2008' could not be found in src/index.md.
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/ZXtrs/src/citations.jl:414
┌ Warning: reference for 'Boumal:2023' could not be found in src/index.md.
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/ZXtrs/src/citations.jl:414
[ Info: Expanding citations in tutorials/StochasticGradientDescent.md
```

as well as later the warnings that the `@citet` links are invalid urls. Does `@citet` maybe not yet work? Hm the same happens with `[Boumal:2023](@cite)` in my markdown I get the warning as above and 

```
┌ Warning: invalid local link: unresolved path in index.md
│   link.text =
│    1-element Vector{Any}:
│     "doCarmo:1992"
│   link.url = "@cite"
└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/H5y27/src/Writers/HTMLWriter.jl:2081
┌ Warning: invalid local link: unresolved path in index.md
│   link.text =
│    1-element Vector{Any}:
│     "AbsilMahonySepulchre:2008"
│   link.url = "@cite"
└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/H5y27/src/Writers/HTMLWriter.jl:2081
┌ Warning: invalid local link: unresolved path in index.md
│   link.text =
│    1-element Vector{Any}:
│     "Boumal:2023"
│   link.url = "@cite"
└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/H5y27/src/Writers/HTMLWriter.jl:2081
```

but the bibliography is displaying correctly all these three entries (and none more from the bible).

**Comment by kellertuer** [comment]
Hm, yes, I can not get the text references to work in any of the reference styles mentioned in the docs, the Bibliography at the end of the page does work however. This is a bit unfortunate.

**Comment by goerz** [comment]
Yeah, there are some issues with `DocumenterCitations`, respectively the underlying [Bibliography.jl](https://github.com/Humans-of-Julia/Bibliography.jl)/[BibParser](https://github.com/Humans-of-Julia/BibParser.jl) being finicky with the `.bib` content it can process. People have some wild syntax in their `.bib` files!

Luckily, you can just clean up your `.bib` file to make it work 😉. None of these extra braces should actually be there (there is no capitalization, like acronyms, to preserve here), and the double braces like `{{Introduction}}` *definitely* shouldn't be there. In fact, `{{Introduction}}` arguably is handled correctly: with the double braces, you're indicating that you want to keep the inner braces. So Zotero should improve their export.

We do have some heuristics in place for handling braces, but they don't include braces over  multiple words, which is why they're not removed from "Smooth Manifolds" and "Cambridge University Press". *Maybe* we can improve that, but it would actually be much better if this was handled transparently by the underlying `Bibliography.jl`.

**Comment by goerz** [comment]
There's a limit to what we can do here, since there's no LaTeX parser for Julia. If someone were to implement one, this would be an entirely different story. Without that, there's always going to be cases where you have to tweak the `.bib` file to get the same result as you would get in LaTeX.

**Comment by kellertuer** [comment]
Sadly this is not “wild syntax” but curly braces are the official way to keep Capitalisation, especially for names and such.

The problem with “cleaning up” is that the Zotero export is an automatic one that is run when I add a reference (since I want to use it in my documentation), so that would mean I have to clean up my whole reference list whenever I want to add something?

Double braces is what Zenodo (even the one called “Better bib” does.

**Comment by kellertuer** [comment]
But of course you are right, both in “fixing other programs silly exports” as well as in your personal efforts (time-wise) in general there are limitations, I can totally understand that and I am happy that we have a very good step forwards with this package in having citations in docs :)

**Comment by goerz** [comment]
> Sadly this is not “wild syntax” but curly braces are the official way to keep Capitalisation, especially for names and such.

I'm sorry, I didn't mean to imply that this was a particular example of "wild syntax". And I agree that we should handle braces better.

One area where people go wild is accented characters. BibTeX used to be ascii-only, and the official way to do accented characters is described at https://www.bibtex.org/SpecialSymbols/. But there's other variations like `{\'o}` that work, and weirder stuff with multiple levels of braces. None of that is necessary anymore: I haven't come across a LaTeX installation that doesn't handle unicode bibtex out of the box, in a long time.

Fundamentally, though, (as far as I understand), BibTeX handles one level of braces to protect capitalization, but after that the fields are simply passed to LaTeX. I'm pretty sure that's what happens with the double-braces: the first level of braces is stripped out by BiBTeX and the second level is then just ignored by LaTeX itself. Beyond that, I'm sure there's someone who has actual macro calls in their bibtex fields (like `\textit`, siunitx macros), and this is not something we'll be able to handle. What happens in `DocumenterCitations` is that we can process the raw field text a bit (stripping out braces, for example), but after that, the string is just plain text, or markdown to be more precise. I should probably clarify this a bit more [in the documentation](https://juliadocs.org/DocumenterCitations.jl/stable/syntax/#Syntax-for-the-.bib-file). Capitalization in DocumenterCitations will always be preserved, so there's generally no need to use braces (although it's still a good feature to have, just for compatibility). You're also strongly encouraged to use unicode as much as possible instead of LaTeX commands or escape sequences.

As I said, processing the raw (LaTeX) text should be improved. I'll just have to do a proper letter-by-letter parser. Nested braces is something that you famously can't do with a simple regex (which is what we have now). The parser will also have to be able to recognize inline math, since that's something we want to perfectly preserve (including braces). Everywhere else, we should just strip out braces. I wouldn't mind if that processing was done in `Bibliography.jl`, but I'll have to get in touch with the maintainer to see what they think.


> The problem with “cleaning up” is that the Zotero export is an automatic one that is run when I add a reference (since I want to use it in my documentation), so that would mean I have to clean up my whole reference list whenever I want to add something?

Oh, definitely not. What I had in mind is that you keep a `.bib` file for the Manopt documentation, separate from the `.bib` file that Zotero puts out. If want to add a reference, add it in Zotero, open the `.bib` file that Zotero generators in a text editor, and copy the entry to the `.bib` file for the Manopt documentation. Then you can "clean" it there, once.


> Double braces is what Zenodo (even the one called “Better bib” does.

I've seen even pretty widely used tools write out pretty questionable `.bib` code. And don't even get me started on the garbage that publishers let you download off their website! That's something I personally handle with a [getbibtex](https://github.com/goerz/getbibtex) script I'm also [advertising in the documentation](https://juliadocs.org/DocumenterCitations.jl/stable/syntax/#Syntax-for-the-.bib-file)

My general recommendation (and what I do) is to copy the bib code exported by your reference manager, and put that in a separate `.bib` file for any specific paper (or software project, in this case), and to clean it up manually in a text editor.

**Comment by kellertuer** [comment]
Concerning wild characters (being German like you I think, ü for example – living in Norway also something like ø) are resolved by BibLaTeX (which is anyways my favourite Bib format), which we do not have a parser for.
From the current parser, something like `{\"a}` is kept as is and also shown in HTML here like this.
Sure I use UTF8 by now as well.

All your arguments are valid, if I would write my bibtex entries by hand I would follow all those rules – the problem is really that I am planning to use some software to keep one archive of literature (and export to paper folders, documentation,...) – and then Zotero (sorry not zenodo) does this strange stuff.

I have some scripts here as well from a previous group I was in (e.g. some `doi2bib` things).

My only argument, where I do not agree is “clean it up manually” because that means I either remember “ah I had this entry cleaned for that paper and can copy it from there” (that's what I do for now for the docs) or clean them multiple times – I prefer to do neither of that.

**Comment by goerz** [comment]
I sympathize. Just be aware that there's some other just plain bugs in the underlying `BibParser`: https://github.com/Humans-of-Julia/BibParser.jl/issues

Even in the example `.bib` file I had to work around that: https://github.com/JuliaDocs/DocumenterCitations.jl/blob/a1bf28692a6fc66bcb34b904ced3d5ad18c9169c/docs/src/refs.bib#L137-L138

Hopefully, this situation will improve over time

**Comment by kellertuer** [comment]
You are right, this is probably more an issue about that package (if you look closely, there is an issue about BibLaTeX – by actually me).
I think we could close this one and I open the curly brace thing there maybe.

**Comment by goerz** [comment]
Related issue (pretty old): https://github.com/Humans-of-Julia/Bibliography.jl/issues/9
