### ISSUE TITLE
More consistent formatting of articles and other types

### ISSUE THREAD

**Issue by lgoettgens** [JuliaDocs/DocumenterCitations.jl#73]
Originally reported in https://github.com/oscar-system/Oscar.jl/issues/3760.

We would like to streamline how our bibliography (ref https://docs.oscar-system.org/dev/references/) looks like, in particular, we would like to have the href for all bib entry types on the title. This works for everything so far, apart from the article type.
We mostly contain DOIs and no URLs (there is no entry that has both), so it would be great to have the first available link on the title, as is already done in https://github.com/JuliaDocs/DocumenterCitations.jl/blob/de9fd1fb2b9b453d7fc26009a0253b113dd42c08/src/formatting.jl#L207 for all other bib entry types.
This would make the aesthetics of the references page a lot more coherent.

**Comment by goerz** [comment]
The current formatting is definitely by design. I'm generally guided by [RevTeX](https://journals.aps.org/revtex) with the formatting, which links the article DOI via the "published in" information. The ability to link both a URL and a DOI is also a design goal. This leaves only the title as a second link location for articles. Conversely, non-articles don't necessarily have sufficient "published in" information to serve as link text, so there, the title becomes the primary link location.

Of, course, all of this is partly a matter of taste, but I'm not very inclined to change this. I'm absolutely open to adding options, or changing the code in some way, to make it easier to modify the behavior with a custom style. In general, I suspect such a custom style might have problems with linking both a URL and a DOI. If a particular project like `Oscar.jl` is careful only to have on or the other, consistently linking only from the title seems sensible.
